### PR TITLE
Bot Route (still working on it)

### PR DESCRIPTION
**Pull request by sohank1**
Im still working on this. If u wanna help just commit on the branch. Also please **commit on this branch with some error codes** for each **res.status()**
Thanks!

### CODE REVIEW

**Comment by CreeperPlanet26** [comment]
I am currently working on the get for this

**Comment by CreeperPlanet26** [comment]
I have finished the get and post for these

**Comment by CreeperPlanet26** [comment]
I have finished the GET api/bot with no id please review to code

**Comment by CreeperPlanet26** [comment]
Here are the error codes:

400 Bad Request. ...
401 Unauthorized. ...
403 Forbidden. ...
404 Not Found. ...
500 Internal Server Error. ...
502 Bad Gateway. ...
503 Service Unavailable. ...
504 Gateway Timeout.

**Comment by Maxisthemoose** [comment]
[More Status Codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)

**Comment by CreeperPlanet26** [comment]
Nice it's fixed

**Comment by CreeperPlanet26** [comment]
Lets go we got a merge conflict

**Comment by CreeperPlanet26** [comment]
The eslint error should do away now. pull the changes

**Comment by CreeperPlanet26** [comment]
Are we ready to merge?

**Pull request merged**
